FROM node:10.16.0-alpine
#Por padrão, create-react-app define a porta para 3000 quando você inicia o app react, mas configurei para executar ui em 8080 (apenas preferência pessoal) em vez de 3000.
EXPOSE 8080 
RUN mkdir -p /app/public /app/src 
WORKDIR /app
COPY tsconfig.json /app/tsconfig.json #ignore se não tiver reação com typescript 
COPY tslint.json /app/tslint.json #ignore se não tiver reação com typescript
COPY package.json /app/package.json 
COPY package-lock.json /app/package-lock.json
## instale apenas os pacotes definidos no package-lock.json (mais rápido que a instalação normal do npm) 
RUN npm install
# Execute 'npm run dev' quando o contêiner for iniciado. 
CMD ["npm", "executar", "dev"]