version: '3'

services:

  app-backend:
    build: .
    entrypoint: sh -c "npm install && npm start"
    ports:
      - 8000:8000
    volumes:
      - .:/home/node/app-backend

  mongo:
    image: mongo:4.2
    ports: 
      - "27017:27017"
